name: "streaming"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "streaming"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - logs

vars:
  kafka_broker: "broker:9092"
  kafka_schema_registry: "http://schema-registry:8081"

models:
  streaming:
    # Config indicated by + and applies to all files under models/source/
    materialized: view
    source:
      +materialized: source
      +schema: source
    staging:
      +schema: staging
      +materialized: view
    materialize:
      +schema: analytics
      +materialized: materializedview
