name: "streaming"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "streaming"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - logs

models:
  streaming:
    staging:
      # Inbound Kafka topic data to be transformed, and served to materialized tables
      +materialized:
        view
        ## Keeping a subset of row versions in memory,
        ##  to transform, or rollback for partitions/history/change branches
