default:
  outputs:
    prod:
      type: materialize
      threads: 1
      host: <host>
      port: 6875
      user: <user@domain.com>
      pass: <password>
      database: materialize
      schema: public
      # optionally use the cluster connection
      # parameter to specify the default cluster
      # for the connection
      cluster: <prod_cluster>
      sslmode: require
    dev:
      type: materialize
      threads: 1
      host: <host>
      port: 6875
      user: <user@domain.com>
      pass: <password>
      database: <dev_database>
      schema: <dev_schema>
      cluster: <dev_cluster>
      sslmode: require

  target: dev
