streaming:
  outputs:
    sbx:
      type: materialize
      threads: 1
      host: 172.19.0.4
      port: 6877
      user: materialize
      pass: materialize
      database: materialize
      schema: public
      # optionally use the cluster connection
      # parameter to specify the default cluster
      # for the connection
      # cluster: <prod_cluster>
      sslmode: require
  target: sbx
