streaming:
  outputs:
    sbx:
      type: materialize
      threads: 1
      host: localhost
      port: 6877
      # user: <user@domain.com>
      # pass: <password>
      database: materialize
      schema: public
      # optionally use the cluster connection
      # parameter to specify the default cluster
      # for the connection
      # cluster: <prod_cluster>
      sslmode: require
  target: sbx
